### ISSUE TITLE
why not use options for storing and retrieving the api key

### ISSUE THREAD

**Issue by GreenGrassBlueOcean** [jameelalsalam/eia2#2]
Hi,

I was looking at your package and I was wondering why you are storing the api key in the r environment.
Why not storing the api key in the options environment using the following functions?

1. set api key
`SetAPIKey <- function(apikey){
 options(.EIA_KEY = apikey)
}`

2. retrieve api key
`GetAPIKey <- function(){getOption(".EIA_KEY") }`

In this way you don't need to edit the r - environment of every system where the script is running.
But maybe you have a very good reason that I overlooked.

**Comment by jameelalsalam** [comment]
Hi there. My understanding is that there are a number of different options for storing authentication information. I would like to cover some of the most popular/best practice methods but also do what I can to make sure people can use whatever their preferred authentication storage approach is. Right now a user can pass API key to the package functions, which they can store/retrieve in any way they would like, but I understand it is more convenient to leave that to the package.

I have not set up the R options approach before, so I will have to look into it (and how packages handle multiple authentication approaches). I think with the R options approach you would still need to set the option on every system where the script is running though?

**Comment by GreenGrassBlueOcean** [comment]
I have created a pull request how that this would look like.
When I ran r cmd check I noticed there are still some issues regarding documentation and global variables.
Maybe it is an idea I set up a github workflow so that the issues are more clear?

**Comment by jameelalsalam** [comment]
Thanks for the PR. I have implemented an approach (based on the previous eia package) that retrieves the API key from either a package environment (temporarily for the session), R options per your request, or from the system environment variables (my preferred approach). I am going to close this issue and the PR, but please let me know if you have any trouble.

The new functions are called `eia_set_key()` and `eia_get_key()`. If using the options approach, the option name the package uses is EIA_KEY.

Thanks for your interest in the package. I do have on my list to add Github CI, but I would like to do this myself.
